[2024-01-05T17:48:06.659+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T17:48:06.664+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T17:48:06.664+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-05T17:48:06.671+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T17:48:06.673+0000] {standard_task_runner.py:60} INFO - Started process 201 to run task
[2024-01-05T17:48:06.676+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmp3kc58kmv']
[2024-01-05T17:48:06.677+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask send_metadata_to_kafka
[2024-01-05T17:48:06.702+0000] {task_command.py:423} INFO - Running <TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host d23442f9ddc6
[2024-01-05T17:48:06.739+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='dummy_dag' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T17:53:06.982+0000] {logging_mixin.py:188} INFO - Erro ao enviar a mensagem: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
[2024-01-05T17:53:06.992+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-05T17:53:07.008+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dummy_dag, task_id=send_metadata_to_kafka, execution_date=20240101T000000, start_date=20240105T174806, end_date=20240105T175307
[2024-01-05T17:53:07.050+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T17:53:07.065+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
