[2024-01-05T17:56:30.289+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T17:56:30.295+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T17:56:30.295+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 3
[2024-01-05T17:56:30.302+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T17:56:30.305+0000] {standard_task_runner.py:60} INFO - Started process 340 to run task
[2024-01-05T17:56:30.307+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmpfdidsg2s']
[2024-01-05T17:56:30.308+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask send_metadata_to_kafka
[2024-01-05T17:56:30.336+0000] {task_command.py:423} INFO - Running <TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host d23442f9ddc6
[2024-01-05T17:56:30.377+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='dummy_dag' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T18:01:30.578+0000] {dummy_dag.py:19} ERROR - Erro ao enviar a mensagem: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
[2024-01-05T18:01:30.579+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-05T18:01:30.585+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dummy_dag, task_id=send_metadata_to_kafka, execution_date=20240101T000000, start_date=20240105T175630, end_date=20240105T180130
[2024-01-05T18:01:30.613+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T18:01:30.622+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
